### ISSUE TITLE
Doesn't compile on Apple M1 Mac Mini

### ISSUE THREAD

**Issue by risner** [ShorelineCrypto/cheetahcoin#12]
compiling checkpoints.cpp shows errors related to openssl:
In file included from checkpoints.cpp:10:
In file included from cheetahcoin-master/src/main.h:8:
cheetahcoin-master/src/bignum.h:51:24: error: base class has incomplete type
class CBigNum : public BIGNUM
                ~~~~~~~^~~~~~
/opt/homebrew/opt/openssl@1.1/include/openssl/ossl_typ.h:80:16: note: forward declaration of 'bignum_st'
typedef struct bignum_st BIGNUM;

I'm unsure how to resolve.

**Comment by ShorelineCrypto** [comment]
The v2.1.0 release fully support OSX with x86_64 wallet with static linked binary file.  M1 chip OSX also support X86_64 application so that M1 chip Mac should work on v2.1.0 wallet too.
